#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    sum_arr1=0
    sum_arr2=0
    for i in range(n):
        for j in range(n):
            if(i==j):
                sum_arr1=sum_arr1+arr[i][j]
            if(i+j==n-1):
                sum_arr2=sum_arr2+arr[i][j]

    diff=abs(sum_arr1-sum_arr2)
    return diff
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
